---
title: "Interactive Map"
Author: "Arianna Quinn"
output:
  html_document: default
  pdf_document: default
date: "2024-11-15"
---

#PACKAGE LOADING
```{r}
library(leaflet)
library(htmlwidgets)
library(tidyverse)
```

#DATAFRAME
```{r}
df <- read.csv("~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/Master's data set.csv", header=TRUE) #Load in dataframe
```

#CLEANING VARIABLES
```{r}
#Set presence/absence factor levels
df$Presence <- as.factor(df$Expression)
levels(df$Presence) <- list("Absence of Menstrual Taboos"=c("0"),"Presence of Menstrual Taboos"=c("1"))
```

```{r}
#Set level of restriction factor levels
df$Restriction <- ordered(df$Restrictiveness)
levels(df$Restriction) <- list("Absence of Menstrual Taboos"=c("0"),
"Minimally Restrictive Menstrual Taboos"=c("1"), 
"Moderately Restrictive Menstrual Taboos"=c("2"), 
"Severly Restrictive Menstrual Taboos"=c("3"))
```

```{r}
#Set subsistence strategy as a factor
df$Subsistence <- as.factor(df$Subsistence)
levels(df$Subsistence) <- list("Agriculture"=c("1"),
"Horticulture"=c("2"), 
"Hunter-Gatherers"=c("3"), 
"Pastoralism"=c("4"))
df$Subsistence <- factor(df$Subsistence, levels = c("Hunter-Gatherers", "Agriculture", "Horticulture", "Pastoralism"))

#Set biome as a factor
df$Biome <- as.factor(df$Landscape)
levels(df$Biome)
levels(df$Biome) <- list("Deserts"=c("1"),
"Forests"=c("2"), 
"Grasslands"=c("3"), 
"Tundra"=c("4"))
df$Biome <- factor(df$Biome, levels = c("Tundra", "Deserts", "Forests", "Grasslands"))
```

```{r}
# Prepare the text for the tooltip:
mytext <- paste(
   "Culture: ", df$HRAF.culture, "<br/>",
   "Presence: ", df$Expression, "<br/>",
   "Restriction Level of Taboos: ", df$Restrictiveness, "<br/>",
   "Percent Men Married to More Than One Wife: ", df$Men_Poly,"<br/>",
   "Primary Subsistence Strategy: ", df$Subsistence,"<br/>",
   "Biome: ", df$Biome, "<br/>",
   "Landscape: ", df$Landscape,"<br/>",
   "Average Monthly Temperature (celsius): ", df$MeanMonthlyTemperature, "<br/>",
   "Temperature Predictability: ", df$Temperature_Predictability, "<br/>",
   "Temperature Variability: ", df$Temperature_Variance, "<br/>",
   "Average Monthly Precipitation (mL/m2/month): ", df$MeanMonthlyPrecipitation, "<br/>",
   "Precipitaion Predictability: ", df$Precipitation_Predictability, "<br/>",
   "Precipitaion Variability: ", df$Precipitation_Variance, sep="") %>%
  lapply(htmltools::HTML)
```

```{r}
# Final Map
m <- leaflet(data = df) %>% 
  addTiles()  %>% 
  addProviderTiles("OpenTopoMap") %>%
  addCircleMarkers(~long, ~lat, 
  fillOpacity = 0.8, color="black", radius=3.5, stroke=FALSE,
    label = mytext,
    labelOptions = labelOptions( style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "13px", direction = "auto")
  )

m 
```

```{r}
#saveWidget(m, file=paste0( getwd(), "/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/InteractiveMap.html"))
```
