---
title: "Interactive Phylogenetic Tree"
output:
  pdf_document: default
  html_document: default
always_allow_html: true
date: "2024-11-19"
---

#PACKAGE LOADING
```{r}
#Load packages
library(phytools) #Read in phylogeny
library(ape) #For the phylo.vcv function
library(geiger) #For name.check function
library(tidyverse) #For piping command
library(ggraph)
library(igraph)
library(htmlwidgets)
library(phylocanvas)
```

#DATAFRAME
```{r}
df <- read.csv("~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/Master's data set.csv", header=TRUE) #Load in dataframe
```

#PHYLOGENETIC TREE
```{r}
phylo<-readNexus("~/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/Time-calibrated SCCS supertree ultrametric.nex") #Load the phylogeny
```

#MAKE CULTURE NAMES THE ROWNAMES IN DATAFRAME
```{r}
rownames(df) <- df$tip.label #Set rownames in data frame

pop <- df[,2] #Store the population column

str(df) #Look at data frame
```

#CLEAN PHYLOGENETIC TREE FOR ANALYSIS
```{r}
plotTree(phylo) #Look at phylogeny

name.check (phylo,df$tip.label) # check which populations are in the tree but not in the data and remove them; we remove those populations that have missing data for any of the outcomes
MT_Tree <- drop.tip (phylo, tip=c("Abipon", "Abkhaz", "Ajie", "Atayal", "Aweikoma", "Banen", "Basseri", "Bogo", "Cayua", "Fur_Darfur", "Gheg_Albanians", "Haitians", "Hausa", "Hebrews", "Ifugao", "Khalka_Mongols", "Konso", "Lamet", "Mao", "Mbau_Fijians", "MISSING_Botocudo", "MISSING_Kafa_Kaffa", "MISSING_Kutenai", "MISSING_Natchez", "MISSING_Timbira", "MISSING_Twana", "Mundurucu", "Negri_Sembilan", "New_Ireland", "Nicobarese", "Orokaiva", "Palauans", "Pentecost", "Popoluca", "Punjabi_West", "Rhade", "Russians", "Shilluk", "Suku", "Tobelorese", "Turks",  "Uttar_Pradesh"))

name.check (MT_Tree, df) # OK
write.tree (MT_Tree, "MT.Phylo") # write the reduced tree

phylo.Reduced <- read.tree("MT.Phylo")

phylo_vcv <- vcv.phylo(phylo, cor=TRUE)
phylo.reduced <- vcv.phylo(phylo.Reduced, cor=TRUE)
```

```{r}
plot(phylo.Reduced,type="tidy")
```

```{r}
p <- phylocanvas(phylo.Reduced, treetype = "rectangular", nodestyles = NULL,
nodesize = 30, textsize = 30, linewidth = 3, showlabels = TRUE,
alignlabels = TRUE, showhistory = FALSE, showcontextmenu = TRUE,
showscalebar = FALSE, width = NULL, height = NULL, elementId = NULL )

p
```

```{r}
#saveWidget(p, file=paste0( getwd(), "/Desktop/Menstrual taboos/R CODE DATA FILES (USE)/InteractiveMap.html"))
```
